name = "backend"
compatibility_date = "2023-12-01"

[[r2_buckets]]
binding = 'R2_UPLOAD'
bucket_name = 'blog-app-bucket'

[vars]
DATABASE_URL=""

JWT_SECRET="secret"
OPENAI_API_KEY=""
R2_SUBDOMAIN_URL="https://pub-f4df79dafd534d86873fafaeb876140b.r2.dev"